VCC-2970 VCC-2968 Add a select-only variant; add additional keyboard interaction
uConnect/combobo pull request #22
Opened 2024-04-05 17:56 UTC by stephymiehle

When the text input is deactivated, the combobox works like a `<select>`.

The input is replaced with a `div`, then all of the appropriate interactions and attributes are added to the `div`. Notably, this also brings a lot of `select`-specific behavior to the `div`.

Even though the text input is not visible, we still have to use familiar keyboard patterns; see https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/#kbd_label

2024-04-08 08:09 UTC, Farsad requested changes
@stephymiehle Thank you for the update. 

I encountered two issues during testing. Firstly, when multiselection is enabled, the text for selected items wraps. 
<img width="313" alt="Screenshot 2024-04-08 at 09 00 38" src="https://github.com/uConnect/combobo/assets/437655/3452be1c-d745-4262-b04e-c9d7aaa3c01c">


Secondly, there is an error when using ESC to close the dropdown.
<img width="374" alt="Screenshot 2024-04-08 at 09 00 57" src="https://github.com/uConnect/combobo/assets/437655/ce7ac1e8-f577-4540-97ea-a6259d2d30b8">


If the Combobo is initialized on the HTML without a select element, no data will be posted on form submission. Would it be possible to keep the input and change it to a hidden input?

Additionally, I suggest renaming the 'selectOnly' configuration to something more clear, such as 'noInput'.

2024-04-09 03:45 UTC, stephymiehle commented
Thanks @Farsad! Those issues are updated. Now that we're retaining a hidden `<input>` for form submissions, I'm not sure that "noInput" would be a good fit either.

I came across the "Select-Only" terminology from the [W3C](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/).

In [another discussion on W3C](https://github.com/w3c/aria-practices/issues/1026), this was first called a "read-only combobox" and changed to "select-only" because `readonly` typically means something different.

I've seen this terminology used from other accessibility bloggers and developers, but usually in reference to the W3C example.

I agree that it's a funny fit when we are adding `<select>`-initialized comboboxes too, but haven't seen another term commonly used.

2024-04-09 07:51 UTC, Farsad approved these changes

2024-04-09 18:07 UTC, vicaraya approved these changes

2024-04-09 18:08 UTC, merged